In [ ]:
# -*- coding: utf-8 -*-
"""
Created on Sat Mar 05 16:35:30 2016

@author: maite
"""
import os
import cv2
import numpy as np

CV_CAP_PROP_FRAME_COUNT = 7
CAP_PROP_FPS = 5
CAP_PROP_CONVERT_RGB = 16
CAP_PROP_POS_MSEC = 0

separator = "/"
videoFolder = "gamesa_videos"
videoName = "PALA"
videoFormat = ".mp4"

imageExtension = ".png"
imagesFolder = "imgs" + videoName
print imagesFolder

#comprobar si existe la carpeta para guardar los frames del video. En caso negativo, crear la carpeta
if not os.path.exists(imagesFolder):
    os.makedirs(imagesFolder)

#concatenacion del nombre del fichero
strVideo = videoFolder + separator + videoName + videoFormat
print strVideo

#abrir el video
cap = cv2.VideoCapture(strVideo)

cap == False

#si el video no se abre aparece un mensaje de error y se cierra la aplicación
if (cap is False):
    print "No se ha podido abrir el video {}".format(strVideo)
    #return -1

print "video abierto: {}".format(cap.isOpened())

#obtener propiedades del video
frames = cap.get(CV_CAP_PROP_FRAME_COUNT)
fps = cap.get(CAP_PROP_FPS)

#print frames
#print fps

#params = list()
#params.append(cv2.IMWRITE_PNG_COMPRESSION)
#params.append(8)

#contador de imagenes guardadas
i = 0
success, frame = cap.read()

#while( frame is not None and i < 50 ) :
while( success ) :

    #modificar el nombre de la imagen
    imageName = "{}{}{}{}{}".format(imagesFolder, separator, videoName, i,imageExtension)

    #flags = [i for i in dir(cv2) if i.startswith('COLOR_')]
    #print flags

    #cv2.imshow(imageName, frame)
    cv2.imwrite(imageName, frame)

    #mostrar la imagen obtenida
    #cv2.namedWindow(imgName, 1)
    #cv2.imshow(imgName, frame)
    success,frame = cap.read()
    i += 1
    
print "{} imagenes obtenidas del video {}".format(i, videoName)
cv2.imshow(imageName, frame)
k = cv2.waitKey(0) & 0xFF

#liberar recursos
cap.release()
#cv2.destroyAllWindows()

In [5]:
import cv2
import math

separator = "/"
videoFolder = "gamesa_videos"
videoName = "PALA"
videoFormat = ".mp4"

videoFile = videoFolder + separator + videoName + videoFormat

cap = cv2.VideoCapture(videoFile)
frameRate = cap.get(5) #frame rate
#while(cap.isOpened()):
frameId = cap.get(1) #current frame number
ret, frame = cap.read()
if (ret != True):
    print "first if"
    #break
if (frameId % math.floor(frameRate) == 0):
    filename = "image_" +  str(int(frameId)) + ".jpg"
    print filename
    cv2.imwrite(filename, frame)
cap.release()
print "Done!"

image_0.jpg
Done!


In [15]:
imageName = "imgsPALA\PALA20.jpg"

print imageName
image = cv2.imread(imageName)
print image

#print size(image)

cv2.imshow("imagen", image)
cv2.waitKey(0)
#cv2.waitKey(1000)
#cv2.destroyAllWindows()

imgsPALA\PALA20.jpg
[[[196 148 112]
  [196 148 112]
  [196 148 112]
  ..., 
  [233 195 153]
  [233 195 153]
  [233 195 153]]

 [[196 148 112]
  [196 148 112]
  [196 148 112]
  ..., 
  [233 195 153]
  [233 195 153]
  [233 195 153]]

 [[196 148 112]
  [196 148 112]
  [197 149 113]
  ..., 
  [233 195 153]
  [233 195 153]
  [233 195 153]]

 ..., 
 [[ 68  88  89]
  [ 71  88  91]
  [ 64  81  84]
  ..., 
  [102 117 126]
  [103 118 127]
  [101 116 125]]

 [[ 63  81  82]
  [ 64  82  83]
  [ 65  82  85]
  ..., 
  [ 97 112 121]
  [ 96 111 120]
  [ 94 109 118]]

 [[ 63  81  82]
  [ 59  77  78]
  [ 63  80  83]
  ..., 
  [ 91 106 115]
  [ 93 108 117]
  [ 97 112 121]]]


-1